spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

#    hibernate:
#      ddl-auto: validate

#  datasource:
#    url: jdbc:mysql://localhost:3306/testDb
#    username: root
#    password:
